import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import "./styles.css"
import Navbar from "../components/navbar"
import Footer from "../components/home/footer"

// Import Swiper styles
import "swiper/css"
import "swiper/css/autoplay"
import "swiper/css/free-mode"
import "swiper/css/scrollbar"
import Provider from "@/components/provider"
import { Session } from "next-auth"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
    session,
}: Readonly<{
    children: React.ReactNode
    session: Session
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
            >
                <Provider session={session}>
                    <Navbar />
                    <main className='flex-grow h-full'>{children}</main>
                    <Footer />
                </Provider>
            </body>
        </html>
    )
}
